### ISSUE TITLE
riff tries to allocate a huge amount of memory when diffing large files

### ISSUE THREAD

**Issue by classabbyamp** [walles/riff#35]
This happens in at least the following modes of operation when diffing large files:
- `diff -u file1 file2 | riff`
- `riff file1 file2`

This happens on the latest release but also happens in every version going back to 2.0. (built with `cargo build --release`)
```
$ riff --version
riff 2.22.0

$ riff omegat-sf.txt omegat-gh.txt
memory allocation of 308691186848 bytes failed
zsh: IOT instruction  riff omegat-sf.txt omegat-gh.txt
```
(that's 308GB)

[`riff omegat-sf.txt omegat-gh.txt` strace (tarball, it's very large unpacked)](https://github.com/walles/riff/files/10008716/riff.strace.tar.gz)
[omegat-sf.txt](https://github.com/walles/riff/files/10008735/omegat-sf.txt)
[omegat-gh.txt](https://github.com/walles/riff/files/10008736/omegat-gh.txt)

**Comment by walles** [comment]
Thanks for the repro case, this does indeed work badly, and `riff` should be able to handle input like this.

For some context, `riff`'s work scales with the size of the diff hunks. Since these files have almost no similar lines, the diff ends up in basically one (by diff standards) huge hunk, which `riff` doesn't deal with.

The "fix" I can see here would be for `riff` to try to detect this situation and simply not do any special highlighting in this case.

That would fix the crash.
