### ISSUE TITLE
[feature request] side-by-side mode

### ISSUE THREAD

**Issue by roland-5** [walles/riff#61]
I'm not sure if this would fit into the philosophy of this application, but if so, I would love to see the option to compare differences side by side: on the left what was removed, and on the right what was added.

**Comment by walles** [comment]
My opinion is that side-by-side would not fit with the philosophy.

For some history, before I came up with `riff` I had been thinking about how to view diffs in a better way, and I was looking for some graphical side-by-side tool for the difficult cases.

Tried a number of options but found none that I liked.

But then I thought about `riff` and made an implementation. And since I started using `riff` I never once felt the need for side-by-side.

So in the end, my opinion (right or wrong) is that side-by-side doesn't help people's understanding of what the differences are. Since implementing + maintaining it would come with a cost, but not have much value (IMO), I would prefer not having it in `riff`.

**Comment by walles** [comment]
Do you have a concrete example where you feel `riff`'s output is harder to understand than some side-by-side view?

**Comment by roland-5** [comment]
Hi @walles. No, it's just my personal preference, which I actually use when I want to fit more text on the screen and feel like I have the file actually open in front of me, so they can go to edit and select the changes I want, remembering them. I use this to compare and then edit text, not code. Cheers and much love `riff`.

**Comment by AndydeCleyre** [comment]
In case anyone seeing this finds it useful, some non-riff side-by-side options are below. I like meld, dunk, and mcdiff:

- [meld](https://gnome.pages.gitlab.gnome.org/meld/), for interactive merging and editing in a GUI. Very git-aware, can launch on a single modified file, or used as difftool and mergetool.
- [dunk](https://github.com/darrenburns/dunk), for viewing in a terminal, can be piped to.
- [vimdiff](https://vimdoc.sourceforge.net/htmldoc/diff.html), for those who vim. Provides interactive merging and flexibility, and requires the original full files (I think).
- `mcdiff`, part of [Midnight Commander](https://midnight-commander.org/), for those who don't vim. Provides interactive merging and editing, and requires the original full files. Default color scheme is unreadable to me, but it has a dozen good ones.
- [xxdiff](https://github.com/blais/xxdiff), I hadn't heard of this one till today, and it seems interesting, but not as easy to do manual edits with as meld.
- kompare and kdiff3 exist, but I've always been horrified by the appearance and difficulty or impossibility of doing basic tasks with them.

---

P.S. I love both riff and moor, thank you very much.
